
spring:
  application:
    name: spring-webflux-guide
  webflux:
    base-path: /api
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb://localhost:27017/test
      database: test
      auto-index-creation: true

logging:
  level:
    io:
      reflectoring: debug
    org:
      springframework:
        web: info
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: debug
    reactor:
      netty:
        http:
          client: debug
server:
  port: 8080
  http2:
    enabled: true
